/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as EndlessRouteImport } from './routes/endless'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayLevelIdRouteImport } from './routes/play.$levelId'
import { Route as CommunityLevelIdRouteImport } from './routes/community.$levelId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const EndlessRoute = EndlessRouteImport.update({
  id: '/endless',
  path: '/endless',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLevelIdRoute = PlayLevelIdRouteImport.update({
  id: '/play/$levelId',
  path: '/play/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityLevelIdRoute = CommunityLevelIdRouteImport.update({
  id: '/$levelId',
  path: '/$levelId',
  getParentRoute: () => CommunityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/editor': typeof EditorRoute
  '/endless': typeof EndlessRoute
  '/how-to-play': typeof HowToPlayRoute
  '/levels': typeof LevelsRoute
  '/stats': typeof StatsRoute
  '/community/$levelId': typeof CommunityLevelIdRoute
  '/play/$levelId': typeof PlayLevelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/editor': typeof EditorRoute
  '/endless': typeof EndlessRoute
  '/how-to-play': typeof HowToPlayRoute
  '/levels': typeof LevelsRoute
  '/stats': typeof StatsRoute
  '/community/$levelId': typeof CommunityLevelIdRoute
  '/play/$levelId': typeof PlayLevelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/editor': typeof EditorRoute
  '/endless': typeof EndlessRoute
  '/how-to-play': typeof HowToPlayRoute
  '/levels': typeof LevelsRoute
  '/stats': typeof StatsRoute
  '/community/$levelId': typeof CommunityLevelIdRoute
  '/play/$levelId': typeof PlayLevelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/customize'
    | '/editor'
    | '/endless'
    | '/how-to-play'
    | '/levels'
    | '/stats'
    | '/community/$levelId'
    | '/play/$levelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/customize'
    | '/editor'
    | '/endless'
    | '/how-to-play'
    | '/levels'
    | '/stats'
    | '/community/$levelId'
    | '/play/$levelId'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/customize'
    | '/editor'
    | '/endless'
    | '/how-to-play'
    | '/levels'
    | '/stats'
    | '/community/$levelId'
    | '/play/$levelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  CustomizeRoute: typeof CustomizeRoute
  EditorRoute: typeof EditorRoute
  EndlessRoute: typeof EndlessRoute
  HowToPlayRoute: typeof HowToPlayRoute
  LevelsRoute: typeof LevelsRoute
  StatsRoute: typeof StatsRoute
  PlayLevelIdRoute: typeof PlayLevelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endless': {
      id: '/endless'
      path: '/endless'
      fullPath: '/endless'
      preLoaderRoute: typeof EndlessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$levelId': {
      id: '/play/$levelId'
      path: '/play/$levelId'
      fullPath: '/play/$levelId'
      preLoaderRoute: typeof PlayLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$levelId': {
      id: '/community/$levelId'
      path: '/$levelId'
      fullPath: '/community/$levelId'
      preLoaderRoute: typeof CommunityLevelIdRouteImport
      parentRoute: typeof CommunityRoute
    }
  }
}

interface CommunityRouteChildren {
  CommunityLevelIdRoute: typeof CommunityLevelIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityLevelIdRoute: CommunityLevelIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRouteWithChildren,
  CustomizeRoute: CustomizeRoute,
  EditorRoute: EditorRoute,
  EndlessRoute: EndlessRoute,
  HowToPlayRoute: HowToPlayRoute,
  LevelsRoute: LevelsRoute,
  StatsRoute: StatsRoute,
  PlayLevelIdRoute: PlayLevelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
