/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as EndlessRouteImport } from './routes/endless'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayLevelIdRouteImport } from './routes/play.$levelId'

const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const EndlessRoute = EndlessRouteImport.update({
  id: '/endless',
  path: '/endless',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLevelIdRoute = PlayLevelIdRouteImport.update({
  id: '/play/$levelId',
  path: '/play/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/endless': typeof EndlessRoute
  '/how-to-play': typeof HowToPlayRoute
  '/levels': typeof LevelsRoute
  '/play/$levelId': typeof PlayLevelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/endless': typeof EndlessRoute
  '/how-to-play': typeof HowToPlayRoute
  '/levels': typeof LevelsRoute
  '/play/$levelId': typeof PlayLevelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/endless': typeof EndlessRoute
  '/how-to-play': typeof HowToPlayRoute
  '/levels': typeof LevelsRoute
  '/play/$levelId': typeof PlayLevelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/endless' | '/how-to-play' | '/levels' | '/play/$levelId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/endless' | '/how-to-play' | '/levels' | '/play/$levelId'
  id:
    | '__root__'
    | '/'
    | '/endless'
    | '/how-to-play'
    | '/levels'
    | '/play/$levelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EndlessRoute: typeof EndlessRoute
  HowToPlayRoute: typeof HowToPlayRoute
  LevelsRoute: typeof LevelsRoute
  PlayLevelIdRoute: typeof PlayLevelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endless': {
      id: '/endless'
      path: '/endless'
      fullPath: '/endless'
      preLoaderRoute: typeof EndlessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$levelId': {
      id: '/play/$levelId'
      path: '/play/$levelId'
      fullPath: '/play/$levelId'
      preLoaderRoute: typeof PlayLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EndlessRoute: EndlessRoute,
  HowToPlayRoute: HowToPlayRoute,
  LevelsRoute: LevelsRoute,
  PlayLevelIdRoute: PlayLevelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
